fixed compiler warning about unused member variable
compiler warning:
- [-Wunused-private-field] / clang 3.8.1 -Wall -Werror

arcadia/astring.h/AString
Member variable `size` is unused.
Was removed in Atlantis' astring.h in
commit 269c345bb1c1e36f3d81d883fdad8b7b040ea873

Removed.

arcadia/astring.h:71:6: error: private field 'size' is not used [-Werror,-Wunused-private-field]