fixed compiler warnings: [-Werror=unused-variable] / gcc 6.3.0 -Wall -Werror
example:
arcadia/army1.cpp:2546:9: error: unused variable ‘max’ [-Werror=unused-variable]