fixed compiler warning about misleading indentation
compiler warning:
- [-Wmisleading-indentation] / gcc

arcadia/unit.cpp/Unit::GetMount
Nested `if` followed by two indented statements,
but without braces around statements.
Second statements sets variable `form`, which references variable `formtype`
in arcadia/soldier1.cpp/Soldier::Soldier.

meaning of `formtype`:
0 => fight_as_foot
1 => fight_as_foot behind
2 => ride
3 => ride behind
4 => fly
5 => fly behind

The inner `if` only limits variable `bonus`,
outer `if` checks if terrain denies flying.
So the second statement belongs to the outer `if`.

Fixed indentation.

arcadia/unit.cpp:2564:4: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]