fixed compiler warning about misleading indentation
compiler warning:
- [-Wmisleading-indentation] / gcc

arcadia/skillshows.cpp/ShowSkill::Report
Fixed indentation. No changes to game logic.

arcadia/skillshows.cpp:363:7: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]

Note: fix indentation? clang-format?