fixed compiler warning: [-Werror,-Wsometimes-uninitialized] / clang 3.8.1 -Wall -Werror
example:
arcadia/runorders.cpp:3328:19: error: variable 'reg' is used uninitialized whenever 'if' condition is false
      [-Werror,-Wsometimes-uninitialized]

Not really fixed. Code is misleading indented. What about reformatting code?

Using nullptr instead of NULL requires compiler flag -std=c++11 (or newer). ToDo at another time.