fixed compiler warning about misleading indentation
compiler warning:
- [-Wmisleading-indentation] / gcc

arcadia/unit.cpp/Unit::Taxers
unit.cpp/Unit::Taxers
Conditions check GameDefs about who can tax, followed by statements
to increase `taxers` and `basetax` accordingly. Due to missing braces
only the first statement actually depends on the condition, while
indentation of statements suggest both statements depend.

Added braces.

arcadia/unit.cpp:2427:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
arcadia/unit.cpp:2430:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
unit.cpp:2127:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
unit.cpp:2130:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]