fixed compiler warnings about comment
compiler warning:
- [-Wcomment] / gcc 6.3.0 -Wall -Werror

arcadia/hexside.cpp
Contains a larger block of code is commented out.
This block of code contains comments; resulting in lines like:
  /* Bridge cannot go to ocean and must go over river or ravine *//*
GCC complains:
arcadia/hexside.cpp:232:1: error: "/*" within comment

Fixed.
Used:
```
 #if 0
 <block of code>
 #endif
```
to comment out code.

Didn't delete, because this looks like something that was never completed.