fixed compiler warning about parentheses
compiler warning:
- [-Wparentheses] / gcc 6.3.0 -Wall -Werror

arcadia/aregion.cpp/ARegionList::IcosahedralNeighSetup
Conditions use bit-AND `&` instead of logical-AND `&&`.
This was already fixed in Atlantis.

Fixed.

arcadia/aregion.cpp:2260:9: error: suggest parentheses around comparison in operand of ‘&’ [-Werror=parentheses]
arcadia/aregion.cpp:2346:10: error: suggest parentheses around comparison in operand of ‘&’ [-Werror=parentheses]