fixed compiler warnings about `delete`s not matching `new`s
compiler warning:
- [-Wmismatched-new-delete] / clang 3.8.1 -Wall -Werror

arcadia/astring.cpp
arcadia/map.cpp
astring.cpp
Memmory allocated using `new[]` was free'd
 with `delete` instead of `delete[]`.

Fixed.

arcadia/astring.cpp:164:2: error: 'delete' applied to a pointer that was allocated with 'new[]'; did you
      mean 'delete[]'? [-Werror,-Wmismatched-new-delete]