fixed compiler warning about indentation
compiler warning:
- [-Wmisleading-indentation] / gcc

parseorders.cpp/Game::ParseOrders
Indentation suggests `if (!pCheck ..` belongs to `if (unit->..`.

Fixed indentation. No changes to game logic.

parseorders.cpp:363:7: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]