silenced compiler warnings: [-Werror=unused-but-set-variable] / gcc 6.3.0 -Wall -Werror
example:
arcadia/monthorders.cpp:652:17: error: variable ‘sk’ set but not used [-Werror=unused-but-set-variable]

Code looks like there was a change not completed.
Using gcc 6.3.0: doesn't support c++17 attribute [[MAYBE_UNUSED]]
Used a Macro to silence warning and for easier find/replace later.