fixed compiler warning about misleading indentation
compiler warning:
- [-Wmisleading-indentation] / gcc

arcadia/unit.cpp/Unit::AdjustSkills
Indentation suggests that the second `if` depends on the first `if`.

Fixed indentation. No changes to game logic.

arcadia/unit.cpp:1547:10: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]

Note: Many `int`s are actually `bool`.